<?php
$form = $this->element;
?>


<div class="container">
    <div class="row">

        
            <?php echo $form->getElement('id_parution'); ?>

        
        <div class="input-group col-lg-8">
            <span class="input-group-addon">Titre</span>
            <?php echo $form->getElement('titre_parution'); ?>

        </div>
        <br>
        <div class="input-group col-lg-8">
            <span class="input-group-addon">Auteur</span>
            <?php echo $form->getElement('auteur_parution'); ?>
        </div>
        <br>
        <div class="input-group col-lg-8">
            <span class="input-group-addon">Date de sortie</span>
            <?php echo $form->getElement('date_parution'); ?>
        </div>
        <br>
        <div class="input-group col-lg-8">
            <span class="input-group-addon">Quantité dispo.</span>
            <?php echo $form->getElement('qte_dispo_parution'); ?>
        </div>
        <br>
        <div class="input-group col-lg-8">
            <span class="input-group-addon">Quantité total</span>
            <?php echo $form->getElement('qte_total_parution'); ?>
        </div>
        <br>
        <div class="input-group col-lg-8">
            <span class="input-group-addon">Thème</span>
            <?php echo $form->getElement('theme_parution'); ?>
        </div>
        <br>
        <div class="input-group col-lg-8">
            <span class="input-group-addon">Collection</span>
            <?php echo $form->getElement('collection_parution'); ?>
        </div>
        <br>
        <div class="input-group col-lg-8">
            <span class="input-group-addon">Editeur</span>
            <?php echo $form->getElement('editeur_parution'); ?>
        </div>
        <br>
        <div class="input-group col-lg-8">
            <span class="input-group-addon">Description</span>
            <?php echo $form->getElement('description_parution'); ?>
        </div>
        <br>
        <div class="input-group col-lg-8">
            <span class="input-group-addon">Publier</span>
            <?php echo $form->getElement('publier_parution'); ?>
        </div>
        <br>
        <div class="input-group col-lg-8">
             <span class="input-group-addon">Image</span>
            <?php echo $form->getElement('image_parution'); ?>
        </div>
        <br>
        <div class="input-group col-lg-8">
            <center>
                <?php echo $form->getElement('enregistrer'); ?>
            </center>
        </div>
        <br>







    </div>
</div>